name: honey
description: The sweet side of testing...
version: 0.0.5
homepage: https://honey.dev
repository: https://github.com/clickup/honey

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  antlr4: ^4.11.1
  characters: ^1.1.0
  collection: ^1.15.0
  flutter:
    sdk: flutter
  intl: ^0.17.0
  package_info_plus: ^1.3.0
  synchronized: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.1.0
