name: honey
description: The sweet side of testing...
version: 0.0.5
homepage: https://honey.dev
repository: https://github.com/clickup/honey

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  antlr4: ^4.11.1
  args: ^2.2.0
  characters: ^1.1.0
  collection: ^1.15.0
  flutter:
    sdk: flutter
  flutter_tools:
    sdk: flutter
  glob: ^2.0.1
  intl: ^0.17.0
  json_annotation: ^4.6.0 
  package_info_plus: ^1.3.0
  path: ^1.8.0
  path_provider: ^2.0.6
  synchronized: ^3.0.0

dev_dependencies:
  build_runner: ^2.2.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.3.1
  very_good_analysis: ^3.1.0
