name: honey_parser
description: Parser for HoneyTalk.
version: 0.0.2
homepage: https://honey.dev
repository: https://github.com/leisim/honey

environment:
  sdk: '>=2.14.4 <3.0.0'

dependencies:
  antlr4: ^4.11.1
  honey_core: ^0.0.2

dev_dependencies:
  test: ^1.19.3
  lints: ^2.0.0

dependency_overrides:
  honey_core: 
    path: ../honey_core