name: honey_core
environment:
  sdk: '>=2.14.4 <3.0.0'

dependencies:
  freezed_annotation:
  json_annotation: ^4.3.0

dev_dependencies:
  lints: ^1.0.0
  build_runner:
  freezed:
  json_serializable:
