name: honey_core
description: Core library for Honey. This library contains models and utility used by other Honey packages.
version: 0.0.2
homepage: https://honey.dev
repository: https://github.com/leisim/honey

environment:
  sdk: '>=2.14.4 <3.0.0'

dependencies:
  freezed_annotation: ^1.0.0
  json_annotation: ^4.3.0

dev_dependencies:
  lints: ^1.0.0
  build_runner: ^2.1.5
  freezed: ^1.0.0
  json_serializable: ^6.0.0
