name: honey_cli
description: Command line utilities for honey
version: 0.0.2
homepage: https://honey.dev
repository: https://github.com/leisim/honey

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter_tools:
    sdk: flutter
  honey_core: ^0.0.2
  honey_parser: ^0.0.2
  freezed_annotation: ^2.1.0
  json_annotation: ^4.6.0
  collection: ^1.15.0
  glob: ^2.0.1
  args: ^2.2.0
  synchronized: ^3.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  build_runner: ^2.2.0
  freezed: ^2.1.0
  json_serializable: ^6.3.1

dependency_overrides:
  honey_core: 
    path: ../honey_core
  honey_parser:
    path: ../honey_parser

executables:
  honey: honey
