name: honey
description: The sweet side of testing...
version: 0.0.5
homepage: https://honey.dev
repository: https://github.com/leisim/honey

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  honey_core: 0.0.5
  freezed_annotation: ^2.1.0
  json_annotation: ^4.7.0
  intl: ^0.17.0
  package_info_plus: ^1.3.0
  collection: ^1.15.0
  characters: ^1.1.0
  path_provider: ^2.0.6
  path: ^1.8.0

dev_dependencies:
  build_runner: ^2.2.1
  freezed: ^2.1.1
  json_serializable: ^6.4.0